## numpy>> numerical python
- by Travis Oliphant
- before 2005 there were special mathematical tools (similar to Tora, Linga)  

# Numpy is The fundamental package for scientific computing with Python
- https://numpy.org/

In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.2'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
lis = [1, 2, 3, "pwskills", 3+5j, True, 1.2] #list stores heterogenous data
type(lis)

list

- ❄️ Numpy stored the data in a numpy array
- ❄️ An array is a container/data structure used to store data of same data type>> homogenous
- ❄️ #why numpy? already we have list
- ☃️ C is one of the fastest programming language after c++
- ☃️ numpy is built using C>> Numpy computation is fast
- ☃️ due to array>>since it stores only homogenous data, numpy array is faster
- ☃️ since it stores homogenous data>> contiguous/continuous memory location
- ❄️ Mathematical computation is fast

In [6]:
l = [1, 2, 3, 4, 5] #numpy array is homogenous>>all elements can be interger, float, string

In [7]:
np.array(l)

array([1, 2, 3, 4, 5])

In [8]:
arr = np.array(l) #numpy.ndarray>>n dimensional array

In [9]:
type(arr)

numpy.ndarray

In [10]:
l = [1, 2, 3, 4, 5, "Alice"] #if even one element is string, all elements will be converted to string
np.array(l)

array(['1', '2', '3', '4', '5', 'Alice'], dtype='<U21')

In [11]:
# cause array stores homogenous data

In [12]:
l = [1, 2, 3, 4, 5, 2.5] # one float makes all elements to float
np.array(l)

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr


array([1, 2, 3, 4, 5])

In [15]:
arr.ndim #arr has only rows

1

In [16]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1.ndim

2

In [19]:
mat = np.matrix([1, 2, 3, 4]) #matrix is a specialised array of 2 dimension

In [20]:
type(mat)

numpy.matrix

In [21]:
mat.ndim

2

In [22]:
mat

matrix([[1, 2, 3, 4]])

In [23]:
#To understand the dimension, see the no of opening/closing square bracket

In [24]:
np.matrix([[[1, 2], [1, 5], [3, 6]]]) #will throw error-matrix must be 2-dimensional

ValueError: matrix must be 2-dimensional

In [25]:
arr3 = np.array([[[1, 2], [1, 5], [3, 6]]])

In [27]:
arr3

array([[[1, 2],
        [1, 5],
        [3, 6]]])

In [26]:
arr3.ndim

3

In [28]:
#more ways to array
l = [1, 2, 3]
np.asarray(l) #initial function asarray to convert to an array, np.array came after this

array([1, 2, 3])

In [29]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [30]:
#asanyarray will contert the input to an ndarray, but pass ndarray subclasses through
#if something is already an array or part of array, it will simply allow to pass through it

In [31]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [32]:
mat


matrix([[1, 2, 3, 4]])

In [33]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [34]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [35]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr

array([1, 2, 3, 4, 5])

In [37]:
#accessing elements of the array
arr[0]

np.int64(1)

In [38]:
#array is mutable
arr[0] = 1000

In [39]:
arr


array([1000,    2,    3,    4,    5])

In [40]:
#a and arr will point to same memory location, so if there is change is a or arr
#it will reflect on both

a = arr 

In [41]:
a

array([1000,    2,    3,    4,    5])

In [42]:
arr

array([1000,    2,    3,    4,    5])

In [43]:
#shallow copy>> change in one array will lead to change in another

In [44]:
a[0] = 5000

In [45]:
a

array([5000,    2,    3,    4,    5])

In [46]:
arr

array([5000,    2,    3,    4,    5])

In [47]:
b = arr.copy() #deep copy>> change in one array will not reflect in another

In [48]:
b

array([5000,    2,    3,    4,    5])

In [49]:
b[0] = 11000

In [50]:
b


array([11000,     2,     3,     4,     5])

In [51]:
arr

array([5000,    2,    3,    4,    5])

In [52]:
#To create an array>> np.array, np.asarray, np.asany array

In [53]:
#multiple approaches to generate any array

In [54]:
arr1 = np.fromfunction(lambda i, j: i==j, (3,3)) #Construct an array by executing a function over each coordinate

In [55]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [56]:
arr1.ndim

2

In [57]:
arr1.shape #shape of array

(3, 3)

In [58]:
arr1.size #no of elements in array

9

In [59]:
#True is stored as 1 and False 0 in python
True-False

1

In [60]:
arr2 = np.fromfunction(lambda i, j: i*j, (3,3))

In [61]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [62]:
arr2.ndim

2

In [63]:
arr2.shape

(3, 3)

In [64]:
arr2.size

9

In [65]:
for i in range(5):
    print(i)

0
1
2
3
4


In [66]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [67]:
(i for i in range(5))

<generator object <genexpr> at 0x0000024038DF7F40>

In [68]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [69]:
iterator = (i for i in range(5))

In [70]:
iterator

<generator object <genexpr> at 0x0000024038DF7C40>

In [71]:
np.fromiter(iterator, float) #Create a new 1-dimensional array from an iterable object.

array([0., 1., 2., 3., 4.])

In [72]:
np.fromstring('22 23 24', sep = " ")

array([22., 23., 24.])

In [73]:
np.fromstring('22 23 24', sep = " ", dtype = int) #by default is float, values inside string should be nuerical

array([22, 23, 24])

In [74]:
#for string character you have to use split
string = "Alice, Jack, Stanly"
string.split(",")

['Alice', ' Jack', ' Stanly']

In [75]:
np.array(string.split(","))

array(['Alice', ' Jack', ' Stanly'], dtype='<U7')

In [76]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
#another method of numpy to generate a squesnce of nuumber

In [83]:
#other method of numpy >> To generate a sequence of number
np.arange(1, 10) #arange returns evenly spacified values within a given interval, by default step is 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [81]:
np.linspace(1, 5, 10) # give me 10 numbers between 1 to 5 with equal spacing

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])