In [1]:
import numpy as np

In [ ]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.
a    # it is defualt float type

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
b = np.zeros((3,4))

In [7]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b.ndim

2

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.twos(4)  #doesn't exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.array([[2, 2, 2,], [2, 2, 2]])  # 2d array

array([[2, 2, 2],
       [2, 2, 2]])

In [14]:
arr = np.zeros((3, 4))

In [15]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr.ndim

2

In [17]:
#3 dimensionaly array
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr = np.zeros((3, 3, 4))

In [20]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
arr.ndim

3

In [22]:
np.zeros((1, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
b = np.zeros((1, 1, 3, 3))

In [24]:
b

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [25]:
b.ndim

4

In [26]:
c = np.zeros((1, 1, 1, 3, 3))

In [27]:
c

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [28]:
c.ndim

5

In [29]:
arr = np.zeros((3, 4))

In [30]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [32]:
a = arr+5

In [33]:
a * 2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [34]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [35]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [36]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries.It means entries in the array can be anything random values

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [40]:
#optional>> random module
import random
random.choice((1, 2, 3, 4, 5))

1

In [41]:
random.choice("Alice")

'i'

In [42]:
random.randrange(1, 10)

3

In [43]:
random.random() #a random no generated between 0(included) and 1(excluded)

0.2832911510968895

In [44]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [45]:
random.shuffle(lis)

In [46]:
lis

[3, 5, 2, 1, 4]

In [47]:
random.uniform(7, 14)

10.491885581944066

In [48]:
#random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [49]:
np.random.random_sample()

0.4794430695582873

In [50]:
np.random.random_sample((5, )) #1 dim array of 5 random nos

array([0.96536985, 0.29529902, 0.08870847, 0.87348841, 0.44959736])

In [51]:
np.random.rand(1) #1 dim array of 1 random no

array([0.16023841])

In [52]:
np.random.rand(2, 3)

array([[0.72669566, 0.7577265 , 0.83684378],
       [0.9785154 , 0.48577123, 0.6586215 ]])

In [53]:
np.random.randn(2, 3) #return a sample (or samples) from the "standard normal" distribution.

array([[ 0.13089492,  1.27162616, -0.08000531],
       [ 1.62349387,  1.30415426,  0.44564836]])

In [54]:
np.random.randint(1, 5, size = (3, 4)) #start from 1 and end at 5-1 and give array of shape 3, 4

array([[4, 1, 1, 2],
       [3, 1, 2, 4],
       [3, 4, 1, 4]], dtype=int32)

In [55]:
arr = np.random.randint(1, 5, size = (3, 4))

In [58]:
arr

array([[4, 2, 3, 3],
       [3, 1, 2, 3],
       [3, 3, 2, 4]], dtype=int32)

In [56]:
arr.ndim

2

In [57]:
arr.shape

(3, 4)

In [59]:
arr.size

12

In [60]:
arr

array([[4, 2, 3, 3],
       [3, 1, 2, 3],
       [3, 3, 2, 4]], dtype=int32)

In [61]:
#reshaping of array
arr1 = arr.reshape(2, 6) #Returns an array containing the same data with a new shape.
# orignal size of array was 3*4=12 so new shape should also have same size 2*6=12

In [62]:
arr1

array([[4, 2, 3, 3, 3, 1],
       [2, 3, 3, 3, 2, 4]], dtype=int32)

In [63]:
arr1.size

12

In [64]:
arr1.shape

(2, 6)

In [65]:
arr1.ndim

2

## array size will never change, always reshape parameter should be multiplication of original array size

In [67]:
arr

array([[4, 2, 3, 3],
       [3, 1, 2, 3],
       [3, 3, 2, 4]], dtype=int32)

In [68]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [69]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [70]:
arr.reshape(3,4)

array([[4, 2, 3, 3],
       [3, 1, 2, 3],
       [3, 3, 2, 4]], dtype=int32)

In [71]:
arr.reshape(1, 12)

array([[4, 2, 3, 3, 3, 1, 2, 3, 3, 3, 2, 4]], dtype=int32)

In [72]:
arr.reshape(12, 1)

array([[4],
       [2],
       [3],
       [3],
       [3],
       [1],
       [2],
       [3],
       [3],
       [3],
       [2],
       [4]], dtype=int32)

In [73]:
#case when you dont know in reshape what should be the row or column count
#use any negative value for rows or columns
arr.reshape(4,-1)

array([[4, 2, 3],
       [3, 3, 1],
       [2, 3, 3],
       [3, 2, 4]], dtype=int32)

In [74]:
arr.reshape(4,-100)

array([[4, 2, 3],
       [3, 3, 1],
       [2, 3, 3],
       [3, 2, 4]], dtype=int32)

In [75]:
arr.reshape(-1,4)

array([[4, 2, 3, 3],
       [3, 1, 2, 3],
       [3, 3, 2, 4]], dtype=int32)

In [76]:
arr

array([[4, 2, 3, 3],
       [3, 1, 2, 3],
       [3, 3, 2, 4]], dtype=int32)

In [77]:
arr.reshape(12, 1).base #to see the original array

array([[4, 2, 3, 3],
       [3, 1, 2, 3],
       [3, 3, 2, 4]], dtype=int32)

In [78]:
arr.reshape(2, 2, 3) #multiplication should be equals to arr size

array([[[4, 2, 3],
        [3, 3, 1]],

       [[2, 3, 3],
        [3, 2, 4]]], dtype=int32)

In [79]:
arr.reshape(1, 2, 2, 3)

array([[[[4, 2, 3],
         [3, 3, 1]],

        [[2, 3, 3],
         [3, 2, 4]]]], dtype=int32)

In [80]:
arr.reshape(1, 2, 2, 3).ndim

4

In [81]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[4],
        [2],
        [3]],

       [[3],
        [3],
        [1]],

       [[2],
        [3],
        [3]],

       [[3],
        [2],
        [4]]], dtype=int32)

In [82]:
#conditions on array
arr1=np.random.randint(1, 10, (5, 6))

In [83]:
arr1

array([[2, 8, 2, 9, 6, 7],
       [6, 1, 6, 5, 2, 3],
       [6, 7, 5, 1, 8, 7],
       [4, 8, 2, 7, 4, 4],
       [2, 6, 9, 3, 3, 5]], dtype=int32)

In [84]:
arr1.shape

(5, 6)

In [85]:
arr1.size

30

In [86]:
arr1.ndim

2

In [87]:
arr1

array([[2, 8, 2, 9, 6, 7],
       [6, 1, 6, 5, 2, 3],
       [6, 7, 5, 1, 8, 7],
       [4, 8, 2, 7, 4, 4],
       [2, 6, 9, 3, 3, 5]], dtype=int32)

In [88]:
arr1 > 3

array([[False,  True, False,  True,  True,  True],
       [ True, False,  True,  True, False, False],
       [ True,  True,  True, False,  True,  True],
       [ True,  True, False,  True,  True,  True],
       [False,  True,  True, False, False,  True]])

In [89]:
arr1[arr1 > 3] #select all the elements of arr1 where the condition is true

array([8, 9, 6, 7, 6, 6, 5, 6, 7, 5, 8, 7, 4, 8, 7, 4, 4, 6, 9, 5],
      dtype=int32)

In [90]:
arr1[arr1 < 3]

array([2, 2, 1, 2, 1, 2, 2], dtype=int32)

In [91]:
arr1


array([[2, 8, 2, 9, 6, 7],
       [6, 1, 6, 5, 2, 3],
       [6, 7, 5, 1, 8, 7],
       [4, 8, 2, 7, 4, 4],
       [2, 6, 9, 3, 3, 5]], dtype=int32)

In [92]:
arr1[0]

array([2, 8, 2, 9, 6, 7], dtype=int32)

In [93]:
arr1[1][2]

np.int32(6)

In [94]:
arr1

array([[2, 8, 2, 9, 6, 7],
       [6, 1, 6, 5, 2, 3],
       [6, 7, 5, 1, 8, 7],
       [4, 8, 2, 7, 4, 4],
       [2, 6, 9, 3, 3, 5]], dtype=int32)

In [95]:
arr1[3][1]

np.int32(8)

In [96]:
arr1

array([[2, 8, 2, 9, 6, 7],
       [6, 1, 6, 5, 2, 3],
       [6, 7, 5, 1, 8, 7],
       [4, 8, 2, 7, 4, 4],
       [2, 6, 9, 3, 3, 5]], dtype=int32)

In [97]:
#from oth row to 2nd row
arr1[0:3]

array([[2, 8, 2, 9, 6, 7],
       [6, 1, 6, 5, 2, 3],
       [6, 7, 5, 1, 8, 7]], dtype=int32)

In [98]:
#0 to 2nd row and 0th and 2nd column
arr1[0:3,[0, 2] ]

array([[2, 2],
       [6, 6],
       [6, 5]], dtype=int32)

In [99]:
#slicing on both rows and columns together
arr1

array([[2, 8, 2, 9, 6, 7],
       [6, 1, 6, 5, 2, 3],
       [6, 7, 5, 1, 8, 7],
       [4, 8, 2, 7, 4, 4],
       [2, 6, 9, 3, 3, 5]], dtype=int32)

In [100]:
arr1[0:3, 1:3]

array([[8, 2],
       [1, 6],
       [7, 5]], dtype=int32)

In [101]:
arr1[0:3, [0, 1]]

array([[2, 8],
       [6, 1],
       [6, 7]], dtype=int32)

In [102]:
arr1[0, [1, 3]]

array([8, 9], dtype=int32)

In [103]:
arr1[2:4, [0, 3]]

array([[6, 1],
       [4, 7]], dtype=int32)

In [104]:
arr1[2:5]

array([[6, 7, 5, 1, 8, 7],
       [4, 8, 2, 7, 4, 4],
       [2, 6, 9, 3, 3, 5]], dtype=int32)

In [105]:
arr1[2:5, 0:2]

array([[6, 7],
       [4, 8],
       [2, 6]], dtype=int32)

In [106]:
#mathematical operations on two arrays
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [107]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 1]], dtype=int32)

In [108]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 2]], dtype=int32)

In [109]:
arr1+arr2 #indexwise element addition

array([[2, 4, 3],
       [2, 3, 3],
       [3, 3, 3]], dtype=int32)

In [110]:
arr1-arr2

array([[ 0,  0,  1],
       [ 0,  1,  1],
       [-1,  1, -1]], dtype=int32)

In [111]:
arr1 * arr2 #index wise multiplication

array([[1, 4, 2],
       [1, 2, 2],
       [2, 2, 2]], dtype=int32)

In [112]:
arr1, arr2

(array([[1, 2, 2],
        [1, 2, 2],
        [1, 2, 1]], dtype=int32),
 array([[1, 2, 1],
        [1, 1, 1],
        [2, 1, 2]], dtype=int32))

In [113]:
arr1/arr2 #index wise divison

array([[1. , 1. , 2. ],
       [1. , 2. , 2. ],
       [0.5, 2. , 0.5]])

In [114]:
4/0

ZeroDivisionError: division by zero

In [115]:
arr1/0

C:\Users\user\AppData\Local\Temp\ipykernel_16348\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [116]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 1]], dtype=int32)

## matrix multiplication >>matrix is a specialised 2-d array
## matrix multiplication is different from index wise multiplication

In [117]:
arr1 @ arr2  # in matrix multiplication no of columns in 1st matrix should be equal to no of rows in 2nd matrix

array([[7, 6, 7],
       [7, 6, 7],
       [5, 5, 5]], dtype=int32)

In [118]:
np.dot(arr1, arr2) #another way of matrix multiplication

array([[7, 6, 7],
       [7, 6, 7],
       [5, 5, 5]], dtype=int32)

In [119]:
arr1 * arr2

array([[1, 4, 2],
       [1, 2, 2],
       [2, 2, 2]], dtype=int32)

In [120]:
#broadcasting

In [121]:
arr = np.zeros((3, 4))

In [122]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [124]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [125]:
a = np.array([1, 2, 3, 4])

In [126]:
a

array([1, 2, 3, 4])

In [127]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [128]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [129]:
a = np.array([[1, 2, 3, 4]])

## Transpose>> converting rows to columns and columns to rows  
## Transpose can be use on 2d array only

In [131]:
a

array([[1, 2, 3, 4]])

In [132]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [133]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 1]], dtype=int32)

In [134]:
arr1.T

array([[1, 1, 1],
       [2, 2, 2],
       [2, 2, 1]], dtype=int32)